export const defaultInfo = {
  avatar: 'default-avatar.png',
  fullName: 'Nguyễn Văn Anh',
  position: 'Thực tập sinh',
  gender: 'Nam',
  dob: '01/01/1998',
  address: 'Tân Hòa - Quốc Oai - Hà Nội',
  marital: 'Độc thân',
  childs: 0,
  nationality: 'Việt Nam',
  religion: 'Không',
  phone: '0123456789',
  email: 'anhnv@gmail.com',
  socials: 'facebook.com/anh.nv',
  profile: 'Mong muốn được thực tập tại công ty, học hỏi thêm nhiều kiến thức và kinh nghiệm lập trình, kết hợp với những kiến thức đã học được để đóng góp cho công ty trong quá trình thực tập hè. Hơn thế nữa là được trở thành nhân viên chính thức của công ty.',
  activities: ['Đảm nhận vị trí chủ tịch hội sinh viên khóa 61 Đại học Bách Khoa Hà Nội', 'Đảm nhận vị trí chủ tịch hội sinh viên khóa 61 Đại học Bách Khoa Hà Nội'],
  hobbies: ['Nghe nhạc', 'Nghe nhạc'],
  educations: [
    { school: 'Đại học Bách Khoa Hà Nội', field: 'Cử nhân công nghệ thông tin', start: '01/2016', end: '01/2020', description: '- CPA hiện tại: 3.5\n- Dự kiến ra trường: 01/2021' },
    { school: 'Đại học Bách Khoa Hà Nội', field: 'Cử nhân công nghệ thông tin', start: '01/2016', end: '01/2020', description: '- CPA hiện tại: 3.5\n- Dự kiến ra trường: 01/2021' },
  ],
  works: [
    { company: 'Công ty ABC', position: 'Lập trình viên', start: '01/2016', end: '01/2020', description: '- Lập trình viên chính trong các dự án của công ty\n- Hướng dẫn cho các bạn thực tập sinh mới vào công ty' },
    { company: 'Công ty ABC', position: 'Lập trình viên', start: '01/2016', end: '01/2020', description: '- Lập trình viên chính trong các dự án của công ty\n- Hướng dẫn cho các bạn thực tập sinh mới vào công ty' },
  ],
  projects: [
    { name: 'Đồ án 1', company: 'Đại học Bách Khoa Hà Nội', start: '01/2016', end: '01/2020', description: '- Xây dựng ứng dụng tạo CV\n- Công nghệ sử dụng: Java' },
    { name: 'Đồ án 1', company: 'Đại học Bách Khoa Hà Nội', start: '01/2016', end: '01/2020', description: '- Xây dựng ứng dụng tạo CV\n- Công nghệ sử dụng: Java' },
  ],
  memberships: [
    { role: 'Thành viên', organization: 'Hội lập trình viên Hà Nội', start: '01/2016', end: '01/2020' },
    { role: 'Thành viên', organization: 'Hội lập trình viên Hà Nội', start: '01/2016', end: '01/2020' },
  ],
  additional: 'Mong muốn được thực tập tại công ty, học hỏi thêm nhiều kiến thức và kinh nghiệm lập trình, kết hợp với những kiến thức đã học được để đóng góp cho công ty trong quá trình thực tập hè. Hơn thế nữa là được trở thành nhân viên chính thức của công ty.',
  skills: [
    { name: 'Tiếng Anh', rate: 2.5 },
    { name: 'Tiếng Anh', rate: 2.5 },
  ],
  awards: [
    { name: 'Quán quân MR & MISS', organization: 'Đại học Bách Khoa Hà Nội', year: 2020 },
    { name: 'Quán quân MR & MISS', organization: 'Đại học Bách Khoa Hà Nội', year: 2020 },
  ],
  certificates: [
    { name: 'TOEIC 450', organization: 'IIG Việt Nam', year: 2020 },
    { name: 'TOEIC 450', organization: 'IIG Việt Nam', year: 2020 },
  ],
  scholarships: [
    { name: 'Học bổng tài năng', organization: 'Đại học Bách Khoa Hà Nội', year: 2020 },
    { name: 'Học bổng tài năng', organization: 'Đại học Bách Khoa Hà Nội', year: 2020 },
  ],
  theses: [
    { title: 'Luận văn thạc sĩ', advisor: 'Nguyễn Văn Anh', description: 'Nghiên cứu về lĩnh vực Trí tuệ nhân tạo và Học máy, xây dựng chương trình nhận diện ảnh chân dung người, sử dụng bởi các phần mềm có tính năng tải lên tập tin ảnh.' },
    { title: 'Luận văn thạc sĩ', advisor: 'Nguyễn Văn Anh', description: 'Nghiên cứu về lĩnh vực Trí tuệ nhân tạo và Học máy, xây dựng chương trình nhận diện ảnh chân dung người, sử dụng bởi các phần mềm có tính năng tải lên tập tin ảnh.' },
  ],
  books: ['Anh, N. V. (2020). Phân tích và nhận diện ảnh. Hà Nội: Kim Đồng.', 'Anh, N. V. (2020). Phân tích và nhận diện ảnh. Hà Nội: Kim Đồng.'],
  journals: ['Anh, N. V. (2020). Lập trình hướng đối tượng. Tạp chí công nghệ, 20(1), 8-12.', 'Anh, N. V. (2020). Lập trình hướng đối tượng. Tạp chí công nghệ, 20(1), 8-12.'],
  presentations: ['"Lập trình Java." Hội nghị công nghệ. Hà Nội, 2020.', '"Lập trình Java." Hội nghị công nghệ. Hà Nội, 2020.'],
}

export const viLabel = {
  information: 'Thông tin',
  gender: 'Giới tính',
  dob: 'Ngày sinh',
  address: 'Địa chỉ',
  marital: 'Hôn nhân',
  childs: 'Số con',
  nationality: 'Quốc tịch',
  religion: 'Tôn giáo',
  phone: 'Điện thoại',
  email: 'Email',
  website: 'Website',
  profile: 'Giới thiệu',
  education: 'Học vấn',
  work: 'Kinh nghiệm làm việc',
  project: 'Dự án',
  membership: 'Tổ chức',
  activity: 'Hoạt động',
  additional: 'Thông tin thêm',
  award: 'Giải thưởng',
  certificate: 'Chứng nhận',
  scholarship: 'Học bổng',
  thesis: 'Luận văn',
  publication: 'Xuất bản, thuyết trình',
  hobby: 'Sở thích',
  skill: 'Kỹ năng',
  advisor: 'GVHD',
  book: 'Sách',
  journal: 'Tạp chí',
  presentation: 'Thuyết trình',
}

export const enLabel = {
  information: 'Information',
  gender: 'Gender',
  dob: 'Birthday',
  address: 'Address',
  marital: 'Marital status',
  childs: 'Children',
  nationality: 'Nationality',
  religion: 'Religion',
  phone: 'Tel',
  email: 'Email',
  website: 'Website',
  profile: 'Profile',
  education: 'Education',
  work: 'Work experience',
  project: 'Projects',
  membership: 'Memberships',
  activity: 'Activities',
  additional: 'Additional information',
  award: 'Honors / Awards',
  certificate: 'Certificates',
  scholarship: 'Scholarships',
  thesis: 'Thesis / Dissertation',
  publication: 'Publications / Presentations',
  hobby: 'Interests',
  skill: 'Skills',
  advisor: 'Advisor',
  book: 'Books',
  journal: 'Publications',
  presentation: 'Presentations',
}
